{
  'name':'Member Custom',
  'version': '1.1',
  'description': 'This will customize odoo',
  'author': 'Samra Solomon',
  'depends': [
    'membership',
    'board',
    'auth_signup_verify_email',
    'mail',
    'website',
    'member_dashboard', 
    'reconciliation'
  ],
  'data': [
    'security/security.xml',
    'security/ir.model.access.csv',
    'data/cron_counter.xml',
    'data/res_edlevel.xml',
    'data/field_study.xml',
    'data/payment_fee_configuration.xml',
    'data/inter_personal_skills.xml',
    'data/mail_template_waiting.xml',
    'data/mail_template_reviewed.xml',
    'data/one_city.xml',
    'views/member_fields_modification_views.xml',
    'views/membership_handlers_views.xml',
    'views/candidate_views.xml',
    'views/supporter_views.xml',
    'views/complaint_form_views.xml',
    'views/complaint_template_views.xml',
    'views/member_cells_offices.xml',
    'views/dashboard.xml',
    'views/payment_sequence.xml',
    'views/membership_payment.xml',
    'views/attachment_field_modification_views.xml',
    'views/minor_configurations.xml',
    'report/member_report_views.xml',
    'report/member_report_templates.xml',
    'report/member_report.xml',
    'report/member_detail_template.xml',
    'report/member_tempo_id.xml',
    'report/complaint_report_views.xml',
    'report/complaint_report_templates.xml',
    'report/membership_payment_report.xml'
  ],
  'category': 'Member/Handlers',
  'application': True,
  'installable': True,
  'auto_install': False,
  'sequence': 1
}
